# Generated by Django 5.0.2 on 2024-02-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
