# Generated by Django 5.0.2 on 2024-02-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_assigned_to_alter_task_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'urgent'), (2, 'medium'), (3, 'low'), (4, 'Archived')], null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'To do'), (2, 'In progress'), (3, 'Awaiting Feedback'), (4, 'Done'), (5, 'Archived')], null=True),
        ),
    ]
