# Generated by Django 5.0.2 on 2024-02-18 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_status', '0001_initial'),
        ('tasks', '0008_alter_task_assigned_to_alter_task_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board_status.boardstatus'),
        ),
    ]
