# Generated by Django 5.0.2 on 2024-02-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_status', '0002_remove_boardstatus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardstatus',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
