# Generated by Django 5.0.2 on 2024-02-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_status', '0003_boardstatus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardstatus',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
