# Generated by Django 5.0.2 on 2024-02-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_status', '0004_alter_boardstatus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardstatus',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
